name: Upload Website

on:
  push:
    branches:
    - master
permissions:
  id-token: write # This is required for aws oidc connection
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials from AWS account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE }}
        aws-region: ${{ secrets.AWS_REGION }}
        role-session-name: GitHub-OIDC-TERRAFORM

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./ s3://${{ secrets.AWS_BUCKET_NAME }} --exclude '.github/*' --exclude '.git/*' --delete
